name: parallels
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  awesome_icons: ^1.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_database: ^10.0.16
  firebase_remote_config: ^3.0.15
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  http: ^0.13.5
  iconsax: ^0.0.8
  image_picker: ^0.8.7
  introduction_screen: ^3.1.4
  lottie: ^2.3.0
  page_transition: ^2.0.9
  path_provider: ^2.0.14
  provider: ^6.0.5
  rename: ^2.1.1
  sensors_plus: ^2.0.2
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/
